# Copyright 2023 HM Revenue & Customs
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include "frontend.conf"

appName = "preferences-admin-frontend"
play.http.router = prod.Routes

play.modules.enabled += "uk.gov.hmrc.play.bootstrap.HttpClientV2Module"
play.modules.enabled += "uk.gov.hmrc.preferencesadminfrontend.config.ServiceBindings"
play.modules.enabled += "FrontendModule"

play.filters.headers.contentSecurityPolicy = "default-src 'self' 'unsafe-inline' localhost:9000 localhost:9032 www.google-analytics.com data:"

play.http.errorHandler = "uk.gov.hmrc.preferencesadminfrontend.config.ErrorHandler"

featureFlag {
  migration = false
}

google-analytics {
  token = N/A
  host = auto
}

bulkOptOuts {
   maxUploadEntries = 100
   maxOptOutsPerSecond = 10
}

users = [
    {
      username = "user"
      password = "cHdk"
    },
    {
      username = "admin"
      password = "cHdk"
      roles = "admin"
    },
    {
      username = "solsUser"
      password = "cHdk"
      roles = "sols, generic"
    },
    {
      username = "solsOnlyUser"
      password = "cHdk"
      roles = "sols"
    },
    {
      username = "genericUser"
      password = "cHdk"
      roles = "generic"
    }
]

microservice {
    services {
      entity-resolver {
        host=localhost
        port=8015
      }
      secure-message {
        host=localhost
        port=9051
      }
      preferences {
        host=localhost
        port=8025
      }
      channel-preferences {
        host=localhost
        port=9052
      }
      enrolment-store {
        host=localhost
        port=7775
      }
      email {
         host=localhost
         port=8300
      }
    }
}

play-frontend-hmrc {
  forceServiceNavigation = true
}
